export const TEAM_PICKER_LEAGUES = ["MLB", "NFL", "NBA", "MLS", "NHL"] as const;

export type FavoriteLeagueKey = (typeof TEAM_PICKER_LEAGUES)[number];

export type FavoriteTeamOption = {
  team_id: string;
  team_name: string;
  league: FavoriteLeagueKey;
  logo_url: string | null;
};

const MLB_TEAM_LOGO_OVERRIDES: Record<string, string> = {
  "Arizona Diamondbacks": "/team-logos/mlb-diamondbacks.png",
  "Atlanta Braves": "/team-logos/mlb-braves.png",
  "Baltimore Orioles": "/team-logos/mlb-orioles.png",
  "Boston Red Sox": "/team-logos/mlb-red-sox.png",
  "Chicago Cubs": "/team-logos/mlb-cubs.png",
  "Chicago White Sox": "/team-logos/mlb-white-sox.png",
  "Cincinnati Reds": "/team-logos/mlb-reds.png",
  "Cleveland Guardians": "/team-logos/mlb-guardians.png",
  "Colorado Rockies": "/team-logos/mlb-rockies.png",
  "Detroit Tigers": "/team-logos/mlb-tigers.png",
  "Houston Astros": "/team-logos/mlb-astros.png",
  "Kansas City Royals": "/team-logos/mlb-royals.png",
  "Los Angeles Angels": "/team-logos/mlb-angels.png",
  "Los Angeles Dodgers": "/team-logos/mlb-dodgers.png",
  "Miami Marlins": "/team-logos/mlb-marlins.png",
  "Milwaukee Brewers": "/team-logos/mlb-brewers.png",
  "Minnesota Twins": "/team-logos/mlb-twins.png",
  "New York Mets": "/team-logos/mlb-mets.png",
  "New York Yankees": "/team-logos/mlb-yankees.png",
  Athletics: "/team-logos/mlb-athletics.png",
  "Philadelphia Phillies": "/team-logos/mlb-phillies.png",
  "Pittsburgh Pirates": "/team-logos/mlb-pirates.png",
  "San Diego Padres": "/team-logos/mlb-padres.png",
  "San Francisco Giants": "/team-logos/mlb-giants.png",
  "Seattle Mariners": "/team-logos/mlb-mariners.png",
  "St. Louis Cardinals": "/team-logos/mlb-cardinals.png",
  "Tampa Bay Rays": "/team-logos/mlb-rays.png",
  "Texas Rangers": "/team-logos/mlb-rangers.png",
  "Toronto Blue Jays": "/team-logos/mlb-blue-jays.png",
  "Washington Nationals": "/team-logos/mlb-nationals.png",
};

const withLeague = (league: FavoriteLeagueKey, teamNames: string[]): FavoriteTeamOption[] =>
  teamNames.map((teamName) => ({
    team_id: `${league.toLowerCase()}-${teamName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")}`,
    team_name: teamName,
    league,
    logo_url:
      (league === "MLB" ? MLB_TEAM_LOGO_OVERRIDES[teamName] : null) ??
      `/team-logos/${teamName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")}.png`,
  }));

export const FAVORITE_TEAMS_BY_LEAGUE: Record<FavoriteLeagueKey, FavoriteTeamOption[]> = {
  MLB: withLeague("MLB", [
    "Arizona Diamondbacks",
    "Atlanta Braves",
    "Baltimore Orioles",
    "Boston Red Sox",
    "Chicago Cubs",
    "Chicago White Sox",
    "Cincinnati Reds",
    "Cleveland Guardians",
    "Colorado Rockies",
    "Detroit Tigers",
    "Houston Astros",
    "Kansas City Royals",
    "Los Angeles Angels",
    "Los Angeles Dodgers",
    "Miami Marlins",
    "Milwaukee Brewers",
    "Minnesota Twins",
    "New York Mets",
    "New York Yankees",
    "Athletics",
    "Philadelphia Phillies",
    "Pittsburgh Pirates",
    "San Diego Padres",
    "San Francisco Giants",
    "Seattle Mariners",
    "St. Louis Cardinals",
    "Tampa Bay Rays",
    "Texas Rangers",
    "Toronto Blue Jays",
    "Washington Nationals",
  ]),
  NFL: withLeague("NFL", [
    "Arizona Cardinals",
    "Atlanta Falcons",
    "Baltimore Ravens",
    "Buffalo Bills",
    "Carolina Panthers",
    "Chicago Bears",
    "Cincinnati Bengals",
    "Cleveland Browns",
    "Dallas Cowboys",
    "Denver Broncos",
    "Detroit Lions",
    "Green Bay Packers",
    "Houston Texans",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Kansas City Chiefs",
    "Las Vegas Raiders",
    "Los Angeles Chargers",
    "Los Angeles Rams",
    "Miami Dolphins",
    "Minnesota Vikings",
    "New England Patriots",
    "New Orleans Saints",
    "New York Giants",
    "New York Jets",
    "Philadelphia Eagles",
    "Pittsburgh Steelers",
    "San Francisco 49ers",
    "Seattle Seahawks",
    "Tampa Bay Buccaneers",
    "Tennessee Titans",
    "Washington Commanders",
  ]),
  NBA: withLeague("NBA", [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "LA Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards",
  ]),
  MLS: withLeague("MLS", [
    "Atlanta United",
    "Austin FC",
    "Charlotte FC",
    "Chicago Fire FC",
    "FC Cincinnati",
    "Colorado Rapids",
    "Columbus Crew",
    "D.C. United",
    "FC Dallas",
    "Houston Dynamo FC",
    "Inter Miami CF",
    "LA Galaxy",
    "Los Angeles FC",
    "Minnesota United FC",
    "CF Montreal",
    "Nashville SC",
    "New England Revolution",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City SC",
    "Philadelphia Union",
    "Portland Timbers",
    "Real Salt Lake",
    "San Diego FC",
    "San Jose Earthquakes",
    "Seattle Sounders FC",
    "Sporting Kansas City",
    "St. Louis City SC",
    "Toronto FC",
    "Vancouver Whitecaps FC",
  ]),
  NHL: withLeague("NHL", [
    "Anaheim Ducks",
    "Boston Bruins",
    "Buffalo Sabres",
    "Calgary Flames",
    "Carolina Hurricanes",
    "Chicago Blackhawks",
    "Colorado Avalanche",
    "Columbus Blue Jackets",
    "Dallas Stars",
    "Detroit Red Wings",
    "Edmonton Oilers",
    "Florida Panthers",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montreal Canadiens",
    "Nashville Predators",
    "New Jersey Devils",
    "New York Islanders",
    "New York Rangers",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "San Jose Sharks",
    "Seattle Kraken",
    "St. Louis Blues",
    "Tampa Bay Lightning",
    "Toronto Maple Leafs",
    "Utah Mammoth",
    "Vancouver Canucks",
    "Vegas Golden Knights",
    "Washington Capitals",
    "Winnipeg Jets",
  ]),
};
