export type PodcastFeedCategory =
  | "Science"
  | "True Crime"
  | "Arts"
  | "Business"
  | "Sports"
  | "Politics";

export type PodcastFeedConfig = {
  slug: string;
  title: string;
  publisher: string;
  category: PodcastFeedCategory;
  featured?: boolean;
  feedUrl: string;
  searchTerms?: string[];
};

export const PODCAST_FEEDS: PodcastFeedConfig[] = [
  {
    slug: "the-daily",
    title: "The Daily",
    publisher: "The New York Times",
    category: "Politics",
    featured: true,
    feedUrl: "https://feeds.simplecast.com/54nAGcIl",
    searchTerms: ["the daily", "new york times politics podcast"],
  },
  {
    slug: "up-first",
    title: "Up First",
    publisher: "NPR",
    category: "Politics",
    featured: true,
    feedUrl: "https://feeds.npr.org/510318/podcast.xml",
    searchTerms: ["up first", "npr politics podcast"],
  },
  {
    slug: "npr-politics-podcast",
    title: "NPR Politics Podcast",
    publisher: "NPR",
    category: "Politics",
    featured: true,
    feedUrl: "https://feeds.npr.org/510310/podcast.xml",
    searchTerms: ["npr politics podcast", "politics podcast"],
  },
  {
    slug: "pod-save-america",
    title: "Pod Save America",
    publisher: "Crooked Media",
    category: "Politics",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/podsaveamerica",
    searchTerms: ["pod save america", "politics podcast"],
  },
  {
    slug: "marketplace",
    title: "Marketplace",
    publisher: "Marketplace",
    category: "Business",
    featured: true,
    feedUrl: "https://feeds.publicradio.org/public_feeds/marketplace/podcast.xml",
    searchTerms: ["marketplace business podcast"],
  },
  {
    slug: "planet-money",
    title: "Planet Money",
    publisher: "NPR",
    category: "Business",
    featured: true,
    feedUrl: "https://feeds.npr.org/510289/podcast.xml",
    searchTerms: ["planet money", "business podcast"],
  },
  {
    slug: "freakonomics-radio",
    title: "Freakonomics Radio",
    publisher: "Freakonomics Radio Network",
    category: "Business",
    featured: true,
    feedUrl: "https://feeds.simplecast.com/Y8lFbOT4",
    searchTerms: ["freakonomics radio", "business podcast"],
  },
  {
    slug: "hbr-ideacast",
    title: "HBR IdeaCast",
    publisher: "Harvard Business Review",
    category: "Business",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/HSW7835897477",
    searchTerms: ["hbr ideacast", "harvard business review podcast"],
  },
  {
    slug: "the-journal",
    title: "The Journal.",
    publisher: "The Wall Street Journal",
    category: "Business",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/the-journal",
    searchTerms: ["the journal wsj", "wall street journal podcast"],
  },
  {
    slug: "espn-daily",
    title: "ESPN Daily",
    publisher: "ESPN",
    category: "Sports",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/ESP9794872487",
    searchTerms: ["espn daily", "sports podcast"],
  },
  {
    slug: "the-bill-simmons-podcast",
    title: "The Bill Simmons Podcast",
    publisher: "The Ringer",
    category: "Sports",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/the-bill-simmons-podcast",
    searchTerms: ["bill simmons", "sports podcast"],
  },
  {
    slug: "the-athletic-football-show",
    title: "The Athletic Football Show",
    publisher: "The Athletic",
    category: "Sports",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/the-athletic-football-show",
    searchTerms: ["the athletic football show", "nfl podcast"],
  },
  {
    slug: "science-friday",
    title: "Science Friday",
    publisher: "Science Friday",
    category: "Science",
    featured: true,
    feedUrl: "https://feeds.simplecast.com/fmTl2V0A",
    searchTerms: ["science friday", "science podcast"],
  },
  {
    slug: "short-wave",
    title: "Short Wave",
    publisher: "NPR",
    category: "Science",
    featured: true,
    feedUrl: "https://feeds.npr.org/510351/podcast.xml",
    searchTerms: ["short wave npr", "science podcast"],
  },
  {
    slug: "huberman-lab",
    title: "Huberman Lab",
    publisher: "Scicomm Media",
    category: "Science",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/hubermanlab",
    searchTerms: ["huberman lab", "science podcast"],
  },
  {
    slug: "nature-podcast",
    title: "Nature Podcast",
    publisher: "Nature",
    category: "Science",
    featured: true,
    feedUrl: "https://feeds.nature.com/nature/podcast/current",
    searchTerms: ["nature podcast", "science podcast"],
  },
  {
    slug: "nasas-curious-universe",
    title: "NASA's Curious Universe",
    publisher: "NASA",
    category: "Science",
    featured: true,
    feedUrl: "https://www.omnycontent.com/d/playlist/d49a4a38-cb0f-4d84-bf5d-a9f0001c5f60/4f81f53e-5f40-4317-b04d-ab87013d2333/9dd9e7fd-4f52-47c7-ad2c-ab87013d2352/podcast.rss",
    searchTerms: ["nasa's curious universe", "nasa podcasts", "science podcast"],
  },
  {
    slug: "crime-junkie",
    title: "Crime Junkie",
    publisher: "audiochuck",
    category: "True Crime",
    featured: true,
    feedUrl: "https://feeds.simplecast.com/qm_9xx0g",
    searchTerms: ["crime junkie", "true crime podcast"],
  },
  {
    slug: "casefile-true-crime",
    title: "Casefile True Crime",
    publisher: "Casefile Presents",
    category: "True Crime",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/casefile",
    searchTerms: ["casefile", "true crime podcast"],
  },
  {
    slug: "dateline-nbc",
    title: "Dateline NBC",
    publisher: "NBC News",
    category: "True Crime",
    featured: true,
    feedUrl: "https://podcastfeeds.nbcnews.com/dateline-nbc",
    searchTerms: ["dateline nbc", "true crime podcast"],
  },
  {
    slug: "serial",
    title: "Serial",
    publisher: "Serial Productions",
    category: "True Crime",
    featured: true,
    feedUrl: "https://feeds.serialpodcast.org/serialpodcast",
    searchTerms: ["serial podcast", "true crime podcast"],
  },
  {
    slug: "the-lonely-palette",
    title: "The Lonely Palette",
    publisher: "Hub & Spoke",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/thelonelypalette",
    searchTerms: ["the lonely palette", "art podcast"],
  },
  {
    slug: "artcurious",
    title: "ArtCurious",
    publisher: "ArtCurious",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/artcuriouspodcast",
    searchTerms: ["artcurious", "art podcast"],
  },
  {
    slug: "all-songs-considered",
    title: "All Songs Considered",
    publisher: "NPR",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.npr.org/510019/podcast.xml",
    searchTerms: ["all songs considered", "music podcast"],
  },
  {
    slug: "pop-culture-happy-hour",
    title: "Pop Culture Happy Hour",
    publisher: "NPR",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.npr.org/510282/podcast.xml",
    searchTerms: ["pop culture happy hour", "culture podcast"],
  },
  {
    slug: "design-matters",
    title: "Design Matters",
    publisher: "Design Observer",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/designmatters",
    searchTerms: ["design matters", "design podcast"],
  },
  {
    slug: "the-art-angle",
    title: "The Art Angle",
    publisher: "Artnet News",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/the-art-angle",
    searchTerms: ["the art angle", "art podcast"],
  },
  {
    slug: "99-invisible",
    title: "99% Invisible",
    publisher: "SiriusXM",
    category: "Arts",
    featured: true,
    feedUrl: "https://feeds.simplecast.com/BqbsxVfO",
    searchTerms: ["99% invisible", "design podcast"],
  },
  {
    slug: "bloomberg-businessweek",
    title: "Bloomberg Businessweek",
    publisher: "Bloomberg",
    category: "Business",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/businessweek",
    searchTerms: ["bloomberg businessweek", "business podcast"],
  },
  {
    slug: "pardon-my-take",
    title: "Pardon My Take",
    publisher: "Barstool Sports",
    category: "Sports",
    featured: true,
    feedUrl: "https://feeds.megaphone.fm/pardonmytake",
    searchTerms: ["pardon my take", "sports podcast"],
  },
];

export const PODCAST_CATEGORY_SEARCH_TERMS: Record<PodcastFeedCategory, string[]> = {
  Science: [
    "science friday",
    "nature podcast",
    "nasa podcasts",
    "scientific american podcast",
    "huberman lab",
    "science podcasts",
  ],
  "True Crime": [
    "dateline",
    "crime junkie",
    "casefile",
    "serial",
    "true crime podcasts",
  ],
  Arts: [
    "art podcasts",
    "museum podcasts",
    "culture podcasts",
    "design podcasts",
    "literature podcasts",
  ],
  Business: [
    "bloomberg business podcasts",
    "wsj podcasts",
    "marketplace podcast",
    "planet money",
    "freakonomics",
    "hbr ideacast",
    "business podcasts",
  ],
  Sports: [
    "espn podcasts",
    "cbs sports podcasts",
    "the athletic podcasts",
    "nfl podcast",
    "nba podcast",
    "mlb podcast",
    "nhl podcast",
    "sports podcasts",
  ],
  Politics: [
    "npr politics podcast",
    "politico podcast",
    "fivethirtyeight politics",
    "the daily politics",
    "pod save america",
    "politics podcasts",
  ],
};
